Client:
    type: entity
    table: client
    id:
        idClient:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_client
            generator:
                strategy: SEQUENCE
    fields:
        login:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
        prenom:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        nom:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        adresse:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
        ville:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        codePostal:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
            column: code_postal
        pays:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        telephone:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        civilite:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
    lifecycleCallbacks: {  }
