Pizza:
    type: entity
    table: pizza
    id:
        idPizza:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_pizza
            generator:
                strategy: SEQUENCE
    fields:
        nom:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        prix:
            type: integer
            nullable: true
            options:
                unsigned: false
        description:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        type:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        imgUrl:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: img_url
    lifecycleCallbacks: {  }
